version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./database:/mysite/database
    command:
      - "gunicorn"
      - "mysite.wsgi:application"
      - "--bind"
      - "0.0.0.0:8000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "256k"